export const IDEMPOTENCY_ERROR_CODES = {
  KEY_INVALID_TYPE: "KEY_INVALID_TYPE",
  KEY_REQUIRED: "KEY_REQUIRED",
  KEY_TOO_SHORT: "KEY_TOO_SHORT",
  KEY_TOO_LONG: "KEY_TOO_LONG",
  KEY_INVALID_FORMAT: "KEY_INVALID_FORMAT",

  KEY_REUSED_WITH_DIFFERENT_REQUEST: "KEY_REUSED_WITH_DIFFERENT_REQUEST",
  UNSUPPORTED_REQUEST_VALUE: "UNSUPPORTED_REQUEST_VALUE",
  REQUEST_IN_PROGRESS: "REQUEST_IN_PROGRESS",
  REQUEST_FAILED: "REQUEST_FAILED",
  RECORD_NOT_FOUND: "RECORD_NOT_FOUND",

  STORE_UNAVAILABLE: "STORE_UNAVAILABLE",
  CACHE_UNAVAILABLE: "CACHE_UNAVAILABLE",

  INVALID_CACHED_RESPONSE: "INVALID_CACHED_RESPONSE"
} as const;

export type IdempotencyErrorCode =
  (typeof IDEMPOTENCY_ERROR_CODES)[keyof typeof IDEMPOTENCY_ERROR_CODES];
